name: "Azure Machine Learning Deploy Action"
description: "Deploy a registered model in your Azure Machine Learning Workspace with this GitHub Action"
author: "delpahi/devops/ahmedmahmo"
inputs:
  azure_credentials:
    description: "Azure service principle credencials "
    required: true
  


branding:
  icon: "chevron-up"
  color: "blue"
runs:
  using: "docker"
  image: "Dockerfile"